window.PILLARS_CHRONICLE_DATA = {
  "title": "Pillars of Salt: Los Angeles World of Darkness Chronicle",
  "subtitle": "A pre-V5 citybook timeline and manuscript source",
  "version": "0.1.0",
  "scope": {
    "continuity": "Strict pre-V5 World of Darkness continuity with Pillars of Salt local additions.",
    "publicationGoal": "Storytellers Vault-ready PDF after a later compliance and layout pass.",
    "editorialPolicy": [
      "Use original Pillars prose for all summaries.",
      "Cite sourcebooks and games without reproducing protected prose.",
      "Separate published canon, Pillars additions, and reconciled house continuity.",
      "Exclude V5 metaplot and V5 rules changes."
    ]
  },
  "sources": [
    { "id": "la-by-night", "label": "LA by Night", "type": "sourcebook" },
    { "id": "city-of-angels", "label": "City of Angels", "type": "sourcebook" },
    { "id": "children-of-the-night", "label": "Children of the Night", "type": "sourcebook" },
    { "id": "nights-of-prophecy", "label": "Nights of Prophecy", "type": "sourcebook" },
    { "id": "montreal-by-night", "label": "Montreal by Night", "type": "sourcebook" },
    { "id": "lore-of-the-clans", "label": "Lore of the Clans", "type": "sourcebook" },
    { "id": "shadow-war", "label": "Shadow War", "type": "sourcebook" },
    { "id": "vtmb", "label": "Vampire: The Masquerade - Bloodlines", "type": "video game" },
    { "id": "bns-met", "label": "By Night Studios MET", "type": "rules reference" },
    { "id": "killing-streets", "label": "Killing Streets", "type": "sourcebook" },
    { "id": "anarchs-unbound", "label": "Anarchs Unbound", "type": "sourcebook" },
    { "id": "pillars-notes", "label": "Pillars of Salt local notes", "type": "local continuity" }
  ],
  "eras": [
    {
      "id": "prehistory",
      "title": "Prehistory and Mythic Foundations",
      "range": "1800 BC-1827",
      "summary": "Los Angeles begins as a contested sacred landscape before the Kindred ever arrive. The oldest supernatural claims center on Catalina Island, Tongva sacred practice, and Earthbound attention that will later pull Demon politics into the city."
    },
    {
      "id": "arrival-kindred",
      "title": "Arrival of the Kindred",
      "range": "1828-1916",
      "summary": "The first Cainites arrive through shipwreck, patronage, and ambition. Houghton, Murietta, Don Sebastian, and Fortier become the foundation stones for a city that has not yet decided whether it belongs to princes, barons, monsters, or the dream factory."
    },
    {
      "id": "hollywood-sabbat",
      "title": "Hollywood, Sabbat Infiltration, and Early Power Plays",
      "range": "1917-1942",
      "summary": "The entertainment industry becomes a supernatural engine. Garou, Fallen, Sabbat agents, and ambitious Lasombra recognize that Hollywood can change mortal belief at continental scale."
    },
    {
      "id": "anarch-free-state",
      "title": "The Anarch Free State",
      "range": "1943-1967",
      "summary": "MacNeil's arrival, Don Sebastian's destruction, and the Status Perfectus create the Free State. The new order is never uncontested: Sabbat infiltration, Camarilla observers, and hidden monsters all test its borders."
    },
    {
      "id": "hidden-wars",
      "title": "Crossover Pressure and the Hidden Wars",
      "range": "1968-1997",
      "summary": "Los Angeles becomes a pressure cooker for Earthbound schemes, Setite cults, Changeling courts, Sabbat politics, street wars, and Asian supernatural strategy. By the late 1990s, the Free State is already weaker than its legend."
    },
    {
      "id": "great-leap",
      "title": "The Great Leap Outward and Fall of LA",
      "range": "1998-2001",
      "summary": "The Kuei-jin invasion, Wraithly disasters, Sabbat survival rites, and Camarilla containment strategy tear apart the Free State. The New Promise Mandarinate emerges from exhaustion, collaboration, and divide-and-rule politics."
    },
    {
      "id": "demon-reckoning",
      "title": "Demon Reckoning and Devil's Night",
      "range": "2002",
      "summary": "The Fallen and Earthbound reshape Los Angeles through apocalypse, faith, catastrophe, and Infernal Court politics. The Devil's Night earthquake turns the city into a beacon for supernatural claimants."
    },
    {
      "id": "bloodlines-npm",
      "title": "Bloodlines Era and the New Promise Mandarinate",
      "range": "2003-2014",
      "summary": "The Camarilla, neo-Anarchs, Sabbat, and Kuei-jin fight over the city after the Bloodlines-era crisis. The NPM consolidates, manipulates treaty appearances, and eventually breaks what remains of the old Free State."
    },
    {
      "id": "pillars-setup",
      "title": "Camarilla Return and Pillars of Salt Setup",
      "range": "2015",
      "summary": "Camarilla strikes, Giovanni territorial claims, Sabbat re-emergence, and internal Camarilla betrayal create the opening conditions for the Pillars of Salt chronicle."
    }
  ],
  "events": [
    {
      "id": "quaoar-temple",
      "era": "prehistory",
      "date": "1800 BC",
      "sortYear": -1800,
      "title": "Catalina's First Infernal Shadow",
      "summary": "Tongva sacred work on Catalina Island becomes entangled with the Earthbound Enshagkushanna. A Dreamspeaker's fall gives the island a hidden infernal inheritance long before Los Angeles exists as a modern city.",
      "spheres": ["Demon", "Mage", "Indigenous Myth"],
      "factions": ["Tongva", "Enshagkushanna Cult"],
      "locations": ["Catalina Island"],
      "npcs": ["Enshagkushanna"],
      "sources": ["city-of-angels", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Explains why Catalina remains a pressure point for infernal cults and Earthbound attention."
    },
    {
      "id": "danube-wreck",
      "era": "arrival-kindred",
      "date": "1828",
      "sortYear": 1828,
      "title": "The Danube Wrecks in San Pedro Bay",
      "summary": "Christopher Houghton reaches Los Angeles by disaster rather than conquest when the Danube wrecks near San Pedro. Don Sebastian shelters the survivors, unknowingly opening the door to the city's first vampire power line.",
      "spheres": ["Vampire"],
      "factions": ["Early Kindred", "Don Sebastian's Household"],
      "locations": ["San Pedro Bay", "Los Angeles"],
      "npcs": ["Christopher Houghton", "Don Sebastian"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "published",
      "impact": "Establishes Houghton as the first Cainite anchor for the local timeline."
    },
    {
      "id": "murietta-embrace",
      "era": "arrival-kindred",
      "date": "1853",
      "sortYear": 1853,
      "title": "Joaquin Murietta is Embraced",
      "summary": "Houghton expands his influence by Embracing Joaquin Murietta. The act ties Los Angeles' undead history to outlaw legend, frontier violence, and a city still becoming itself.",
      "spheres": ["Vampire"],
      "factions": ["Early Kindred"],
      "locations": ["Los Angeles"],
      "npcs": ["Christopher Houghton", "Joaquin Murietta"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "published",
      "impact": "Adds a legendary local figure to the city's Cainite ancestry."
    },
    {
      "id": "don-sebastian-embrace",
      "era": "arrival-kindred",
      "date": "1870",
      "sortYear": 1870,
      "title": "Don Sebastian Enters the Blood",
      "summary": "Houghton Embraces Don Sebastian, transforming a mortal host into one of the key undead rulers of early Los Angeles. The gesture creates a future prince and a future revolutionary target.",
      "spheres": ["Vampire"],
      "factions": ["Early Kindred", "Camarilla"],
      "locations": ["Los Angeles"],
      "npcs": ["Christopher Houghton", "Don Sebastian"],
      "sources": ["la-by-night"],
      "continuity": "published",
      "impact": "Sets up the Camarilla order that the Anarch Revolt will later overthrow."
    },
    {
      "id": "houghton-motion-picture",
      "era": "arrival-kindred",
      "date": "1909",
      "sortYear": 1909,
      "title": "Houghton Discovers the Moving Image",
      "summary": "Houghton sees a motion picture and recognizes an industry that can shape appetite, fantasy, and memory. Hollywood becomes more than a mortal business; it becomes an undead obsession.",
      "spheres": ["Vampire"],
      "factions": ["Hollywood Interests"],
      "locations": ["Hollywood"],
      "npcs": ["Christopher Houghton"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "published",
      "impact": "Frames Hollywood as a strategic supernatural asset from the beginning."
    },
    {
      "id": "fortier-arrives",
      "era": "arrival-kindred",
      "date": "1912",
      "sortYear": 1912,
      "title": "Louis Fortier Moves West",
      "summary": "Louis Fortier settles in Los Angeles and begins building the influence that will later let him survive regime changes, invasions, and alliances that destroy less adaptable elders.",
      "spheres": ["Vampire"],
      "factions": ["Independent Kindred"],
      "locations": ["Los Angeles"],
      "npcs": ["Louis Fortier"],
      "sources": ["la-by-night"],
      "continuity": "published",
      "impact": "Introduces one of the city's durable power brokers."
    },
    {
      "id": "glasswalkers-arrive",
      "era": "hollywood-sabbat",
      "date": "1917",
      "sortYear": 1917,
      "title": "Glass Walkers Enter the City",
      "summary": "Don Leandro and his Glass Walker pack arrive in Los Angeles, adding Garou attention to the city's industrial, media, and urban spirit landscape.",
      "spheres": ["Werewolf"],
      "factions": ["Glass Walkers"],
      "locations": ["Los Angeles"],
      "npcs": ["Don Leandro"],
      "sources": ["pillars-notes"],
      "continuity": "published",
      "impact": "Makes the city a cross-sphere battleground before the Anarch Free State exists."
    },
    {
      "id": "caballero-archbishop",
      "era": "hollywood-sabbat",
      "date": "1927",
      "sortYear": 1927,
      "title": "The Caballero Claims Southern California",
      "summary": "A Lasombra known as the Caballero is named Archbishop of Southern California. His campaign for Los Angeles includes grooming Leila Monroe as a ghoul and preparing a longer Sabbat infiltration strategy.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat", "Lasombra"],
      "locations": ["Southern California", "Los Angeles"],
      "npcs": ["The Caballero", "Leila Monroe"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Creates the Sabbat line that will haunt Anarch Los Angeles for decades."
    },
    {
      "id": "lucifer-hollywood",
      "era": "hollywood-sabbat",
      "date": "1930s",
      "sortYear": 1930,
      "title": "The Morningstar Hides in the Dream Factory",
      "summary": "After escaping the Abyss, Lucifer finds shelter in Los Angeles and sees entertainment as a lever for shaping the world. His presence draws Earthbound attention that will later erupt into open catastrophe.",
      "spheres": ["Demon"],
      "factions": ["Fallen", "Earthbound"],
      "locations": ["Hollywood", "Los Angeles"],
      "npcs": ["Lucifer", "Enshagkushanna", "Dagon"],
      "sources": ["city-of-angels"],
      "continuity": "published",
      "impact": "Makes the entertainment industry central to Demon politics in LA."
    },
    {
      "id": "leila-embraced",
      "era": "hollywood-sabbat",
      "date": "1942",
      "sortYear": 1942,
      "title": "Leila Monroe and the Sabbat's Quiet War",
      "summary": "Leila Monroe is Embraced as the Sabbat adopts a deeper infiltration posture toward the Anarchs. The sect prepares to survive by hiding inside the city's revolutionary mythology.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat", "Anarchs"],
      "locations": ["Los Angeles"],
      "npcs": ["Leila Monroe"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Seeds later Sabbat survival networks inside Anarch territory."
    },
    {
      "id": "macneil-arrives",
      "era": "anarch-free-state",
      "date": "1943",
      "sortYear": 1943,
      "title": "Jeremy MacNeil Arrives",
      "summary": "Jeremy MacNeil enters Los Angeles one year before the city erupts. His presence gives the coming revolt a center of gravity and a name that will outlast the revolution itself.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs"],
      "locations": ["Los Angeles"],
      "npcs": ["Jeremy MacNeil"],
      "sources": ["la-by-night", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Introduces the face of the Free State."
    },
    {
      "id": "second-anarch-revolt",
      "era": "anarch-free-state",
      "date": "1944",
      "sortYear": 1944,
      "title": "The Second Anarch Revolt",
      "summary": "Don Sebastian meets Final Death and Camarilla authority collapses in Los Angeles. The Anarch Free State rises from the wreckage as both a political experiment and an unresolved argument.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs", "Camarilla"],
      "locations": ["Los Angeles"],
      "npcs": ["Don Sebastian", "Jeremy MacNeil"],
      "sources": ["la-by-night", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Defines LA as the great Anarch symbol of the western nights."
    },
    {
      "id": "status-perfectus",
      "era": "anarch-free-state",
      "date": "1945",
      "sortYear": 1945,
      "title": "The Status Perfectus is Drafted",
      "summary": "The Revolutionary Council attempts to turn revolt into governance by drafting the Status Perfectus. The document gives the Free State ideals, even as the city remains too fractured to fully embody them.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs", "Revolutionary Council"],
      "locations": ["Los Angeles"],
      "npcs": ["Jeremy MacNeil"],
      "sources": ["la-by-night", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Provides the ideological standard later factions claim, distort, or betray."
    },
    {
      "id": "council-dissolves",
      "era": "anarch-free-state",
      "date": "1947",
      "sortYear": 1947,
      "title": "The Revolutionary Council Dissolves",
      "summary": "The council steps aside, leaving Los Angeles to its barons, ideals, grudges, and personal power blocs. Freedom survives, but so does fragmentation.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs", "Revolutionary Council"],
      "locations": ["Los Angeles"],
      "npcs": [],
      "sources": ["la-by-night", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Explains why the Free State later struggles to answer coordinated threats."
    },
    {
      "id": "victor-girard-press",
      "era": "anarch-free-state",
      "date": "1952",
      "sortYear": 1952,
      "title": "Victor Girard Becomes the Press Liaison",
      "summary": "Victor Girard, childe of Don Sebastian, reveals himself to MacNeil and brokers a role as Kindred liaison to mortal press interests. The old regime's blood finds a place inside the new order.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs", "Camarilla Remnants", "Mortal Press"],
      "locations": ["Los Angeles"],
      "npcs": ["Victor Girard", "Don Sebastian", "Jeremy MacNeil"],
      "sources": ["la-by-night"],
      "continuity": "published",
      "impact": "Shows how old Camarilla lineages survive through utility and compromise."
    },
    {
      "id": "assamite-contract",
      "era": "anarch-free-state",
      "date": "1955",
      "sortYear": 1955,
      "title": "The Failed Contract on MacNeil",
      "summary": "Clan Assamite accepts a Camarilla Inner Circle contract on Jeremy MacNeil. MacNeil survives with Crispus Attucks' help, and the same year Disneyland opens, giving the city another symbolic dream machine.",
      "spheres": ["Vampire"],
      "factions": ["Assamites", "Camarilla", "Anarchs"],
      "locations": ["Los Angeles", "Anaheim"],
      "npcs": ["Jeremy MacNeil", "Crispus Attucks"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "published",
      "impact": "Reinforces the Free State's legend while tying mortal fantasy economies into the setting."
    },
    {
      "id": "amethyst-santa-ana",
      "era": "anarch-free-state",
      "date": "1960",
      "sortYear": 1960,
      "title": "Amethyst Rules Santa Ana",
      "summary": "Amethyst becomes Baron of Santa Ana, strengthening Orange County's place in the broader Los Angeles political map.",
      "spheres": ["Vampire"],
      "factions": ["Anarchs"],
      "locations": ["Santa Ana", "Orange County"],
      "npcs": ["Amethyst"],
      "sources": ["la-by-night"],
      "continuity": "published",
      "impact": "Sets up Orange County as more than a background suburb."
    },
    {
      "id": "valez-archbishop",
      "era": "anarch-free-state",
      "date": "1962",
      "sortYear": 1962,
      "title": "Carolina Valez Takes the Archdiocese",
      "summary": "Carolina Valez becomes Los Angeles' Archbishop, giving the Sabbat a more capable local center of gravity beneath the Free State's surface.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat"],
      "locations": ["Los Angeles"],
      "npcs": ["Carolina Valez"],
      "sources": ["pillars-notes", "montreal-by-night"],
      "continuity": "reconciled",
      "impact": "Connects LA Sabbat history to later Montreal continuity."
    },
    {
      "id": "geduld-arrives",
      "era": "anarch-free-state",
      "date": "1963",
      "sortYear": 1963,
      "title": "David Geduld Watches for the Tower",
      "summary": "David Geduld, a Ventrue Camarilla spy, moves into Los Angeles. The Free State may have rejected princes, but the Ivory Tower never stops taking notes.",
      "spheres": ["Vampire"],
      "factions": ["Camarilla", "Ventrue", "Anarchs"],
      "locations": ["Los Angeles"],
      "npcs": ["David Geduld"],
      "sources": ["la-by-night"],
      "continuity": "published",
      "impact": "Gives the Camarilla an intelligence thread inside Anarch territory."
    },
    {
      "id": "caballero-falls",
      "era": "anarch-free-state",
      "date": "1963",
      "sortYear": 1963.2,
      "title": "The Caballero's Bid Fails",
      "summary": "The Caballero leaves the archbishopric to pursue a western cardinalship and is destroyed by a Court of Blood. His fall clears space for later Sabbat leadership struggles.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat", "Lasombra"],
      "locations": ["Southern California"],
      "npcs": ["The Caballero"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Explains a Sabbat succession gap in Southern California."
    },
    {
      "id": "sabbat-siege-1965",
      "era": "anarch-free-state",
      "date": "1965",
      "sortYear": 1965,
      "title": "The Sabbat Siege and the Watts Fire",
      "summary": "The Sabbat launches a major push into Los Angeles and fails. Mohammed al-Muthlim changes sides during the fighting, hiding beneath an Anarch mask while rising as a Sabbat bishop.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat", "Anarchs", "Crypt's Sons"],
      "locations": ["Los Angeles", "Watts"],
      "npcs": ["Mohammed al-Muthlim", "Archbishop Fuller"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Binds Sabbat infiltration to LA's mortal unrest and Anarch vulnerabilities."
    },
    {
      "id": "manishtusu-setites",
      "era": "hidden-wars",
      "date": "1969",
      "sortYear": 1969,
      "title": "Murder, Serpents, and Street Wars",
      "summary": "The Earthbound Manishtusu comes hunting Lucifer and works through gang violence. In the same period, Dawn Cavanaugh establishes a Temple of Set in Hollywood, adding another predatory faith to the city.",
      "spheres": ["Demon", "Vampire"],
      "factions": ["Earthbound", "Followers of Set", "Hollywood Temple of Set"],
      "locations": ["Hollywood", "Los Angeles"],
      "npcs": ["Manishtusu", "Lucifer", "Dawn Cavanaugh"],
      "sources": ["city-of-angels", "la-by-night"],
      "continuity": "published",
      "impact": "Turns the city's street violence and entertainment culture into overlapping occult fronts."
    },
    {
      "id": "kingdom-pacifica",
      "era": "hidden-wars",
      "date": "1972",
      "sortYear": 1972,
      "title": "California Becomes Pacifica",
      "summary": "The Changelings name California the Kingdom of Pacifica under King Sean. LA's supernatural map gains another courtly layer that rarely aligns with Kindred borders.",
      "spheres": ["Changeling"],
      "factions": ["Kingdom of Pacifica"],
      "locations": ["California", "Los Angeles"],
      "npcs": ["King Sean"],
      "sources": ["pillars-notes"],
      "continuity": "published",
      "impact": "Adds Changeling sovereignty to the city's already crowded occult geography."
    },
    {
      "id": "blood-brothers-torrance",
      "era": "hidden-wars",
      "date": "1974",
      "sortYear": 1974,
      "title": "Double Helix Takes Torrance",
      "summary": "Bishop Mark and his Blood Brother pack claim Torrance, making the South Bay a defined Sabbat pressure point beneath the wider Anarch Free State.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat", "Double Helix", "Blood Brothers"],
      "locations": ["Torrance"],
      "npcs": ["Bishop Mark"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Creates a local domain hook for Sabbat body-horror plots."
    },
    {
      "id": "valez-underground",
      "era": "hidden-wars",
      "date": "1982",
      "sortYear": 1982,
      "title": "Valez Wins the Sabbat Argument",
      "summary": "Carolina Valez challenges Archbishop Fuller, and Cardinal Strathcona removes Fuller as a failure. Valez keeps the Sabbat underground for the next decade instead of wasting strength on open war.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat"],
      "locations": ["Los Angeles"],
      "npcs": ["Carolina Valez", "Archbishop Fuller", "Cardinal Strathcona"],
      "sources": ["pillars-notes", "montreal-by-night"],
      "continuity": "reconciled",
      "impact": "Explains why the Sabbat survives in LA by patience rather than spectacle."
    },
    {
      "id": "pacifica-succession",
      "era": "hidden-wars",
      "date": "1985",
      "sortYear": 1985,
      "title": "Aeron ap Fiona Takes Pacifica",
      "summary": "King Sean is murdered by the Radical People's Front. Queen Aeron ap Fiona takes the throne young, and her later decadence complicates Changeling stability in the region.",
      "spheres": ["Changeling"],
      "factions": ["Kingdom of Pacifica", "Radical People's Front"],
      "locations": ["California", "Los Angeles"],
      "npcs": ["King Sean", "Queen Aeron ap Fiona", "Hamal"],
      "sources": ["pillars-notes"],
      "continuity": "published",
      "impact": "Gives the Changeling court its own internal fracture during LA's late Free State years."
    },
    {
      "id": "rodney-king-riots",
      "era": "hidden-wars",
      "date": "1992",
      "sortYear": 1992,
      "title": "The Rodney King Riots",
      "summary": "The city convulses in mortal unrest, and every hidden faction reads opportunity or warning in the fires. The Sabbat later judges its leadership by whether it exploited the moment.",
      "spheres": ["Mortal", "Vampire"],
      "factions": ["Anarchs", "Sabbat", "Camarilla Observers"],
      "locations": ["Los Angeles"],
      "npcs": ["Carolina Valez", "Mohammed al-Muthlim"],
      "sources": ["la-by-night", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Becomes a political test for Sabbat ambition and Anarch control."
    },
    {
      "id": "valez-exiled",
      "era": "hidden-wars",
      "date": "1993",
      "sortYear": 1993,
      "title": "Valez is Exiled",
      "summary": "Carolina Valez is punished for not using the riots to take Los Angeles. Mohammed al-Muthlim becomes Archbishop, while Valez is later placed over Montreal.",
      "spheres": ["Vampire"],
      "factions": ["Sabbat"],
      "locations": ["Los Angeles", "Mexico", "Montreal"],
      "npcs": ["Carolina Valez", "Mohammed al-Muthlim"],
      "sources": ["montreal-by-night", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Links Los Angeles Sabbat failure to Montreal's later sect politics."
    },
    {
      "id": "extraordinary-commission",
      "era": "hidden-wars",
      "date": "1997",
      "sortYear": 1997,
      "title": "The Extraordinary Commission Looks East to West",
      "summary": "Liejie Li takes command of the Extraordinary Commission with Chiu Bao as her militant first officer. Their mandate is to crack Los Angeles, then use the beachhead against San Diego and San Francisco.",
      "spheres": ["Kuei-jin"],
      "factions": ["Extraordinary Commission", "Quincunx"],
      "locations": ["Los Angeles", "San Diego", "San Francisco"],
      "npcs": ["Liejie Li", "Chiu Bao"],
      "sources": ["shadow-war", "pillars-notes"],
      "continuity": "published",
      "impact": "Sets the strategic logic for the Great Leap Outward."
    },
    {
      "id": "great-leap-begins",
      "era": "great-leap",
      "date": "1998",
      "sortYear": 1998,
      "title": "The Great Leap Outward Hits Los Angeles",
      "summary": "Kuei-jin forces strike the city's unprepared Kin-jin and initially tear through independent vampires and smaller gangs. Resistance hardens around MacNeil, Fortier, Salvador Garcia, and Crispus Attucks.",
      "spheres": ["Kuei-jin", "Vampire"],
      "factions": ["Kuei-jin", "Anarchs", "New Promise Mandarinate"],
      "locations": ["Los Angeles"],
      "npcs": ["Jeremy MacNeil", "Louis Fortier", "Salvador Garcia", "Crispus Attucks"],
      "sources": ["shadow-war", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Begins the military collapse of the Anarch Free State."
    },
    {
      "id": "elijah-ritual",
      "era": "great-leap",
      "date": "1998",
      "sortYear": 1998.2,
      "title": "Elijah's Burial Rite",
      "summary": "The Sabbat prophet Elijah bargains with Manishtusu after foreseeing the sect's destruction in the invasion. A survival ritual hides many Sabbat beneath the city, but the bargain carries a five-year deadline and a predatory cost.",
      "spheres": ["Vampire", "Demon"],
      "factions": ["Sabbat", "Earthbound"],
      "locations": ["Los Angeles", "Burial Sites"],
      "npcs": ["Elijah", "Manishtusu", "Leila Monroe"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Explains why LA Sabbat vanish, then return empowered and traumatized in 2015."
    },
    {
      "id": "yellow-springs-necropolis",
      "era": "great-leap",
      "date": "1999",
      "sortYear": 1999,
      "title": "The Yellow Springs Invades the Necropolis",
      "summary": "The Yellow Springs campaign in the Los Angeles Necropolis collides with the Sixth Great Maelstrom and Avatar Storm. The invasion stalls, casualties mount, and Kuei-jin resources are trapped far from easy reinforcement.",
      "spheres": ["Wraith", "Kuei-jin", "Mage"],
      "factions": ["Yellow Springs", "Crusaders", "Kuei-jin"],
      "locations": ["Los Angeles Necropolis", "Yin World"],
      "npcs": [],
      "sources": ["shadow-war", "nights-of-prophecy"],
      "continuity": "published",
      "impact": "Shows why the Kuei-jin turn from conquest to coalition politics."
    },
    {
      "id": "hao-suicide",
      "era": "great-leap",
      "date": "October 1999",
      "sortYear": 1999.8,
      "title": "Hao Wei-Liang Falls",
      "summary": "After military losses and political pressure, Hao Wei-Liang is forced into ritual suicide. His fall lets the Fence Menders reshape the campaign around controlled collaboration with selected Kin-jin.",
      "spheres": ["Kuei-jin"],
      "factions": ["Fence Menders", "Quincunx", "Kuei-jin"],
      "locations": ["Los Angeles", "Shanghai"],
      "npcs": ["Hao Wei-Liang", "Jiejie Li", "Chiu Bao"],
      "sources": ["shadow-war"],
      "continuity": "published",
      "impact": "Marks the pivot from failed invasion to New Promise Mandarinate strategy."
    },
    {
      "id": "garcia-fortier-deals",
      "era": "great-leap",
      "date": "Late 1999",
      "sortYear": 1999.9,
      "title": "The Divide-and-Rule Bargains",
      "summary": "Kuei-jin diplomats approach Salvador Garcia and Louis Fortier with positions inside a new order. Their choices fracture Anarch unity and give the invaders local shock troops and legitimacy.",
      "spheres": ["Kuei-jin", "Vampire"],
      "factions": ["New Promise Mandarinate", "Anarchs", "El Hermandad"],
      "locations": ["Los Angeles"],
      "npcs": ["Salvador Garcia", "Louis Fortier", "Monkey Trip Wu", "Fun Toy"],
      "sources": ["shadow-war", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Turns Anarch exhaustion into the political death warrant of the Free State."
    },
    {
      "id": "new-years-riots",
      "era": "great-leap",
      "date": "New Year 2000",
      "sortYear": 2000,
      "title": "The New Year's Riots End the Free State",
      "summary": "The New Promise coalition uses chaos to crush or scatter holdouts. Refugees flee west coast cities, Lupines and scourges destroy many survivors, and Los Angeles becomes the Mandarinate's domain in practice.",
      "spheres": ["Kuei-jin", "Vampire", "Werewolf"],
      "factions": ["New Promise Mandarinate", "Anarchs", "Kuei-jin"],
      "locations": ["Los Angeles", "San Francisco", "San Diego"],
      "npcs": ["Monkey Trip Wu", "Fun Toy"],
      "sources": ["shadow-war", "anarchs-unbound"],
      "continuity": "published",
      "impact": "Ends the Anarch Free State as a functioning political force in this continuity."
    },
    {
      "id": "camarilla-response",
      "era": "great-leap",
      "date": "2000",
      "sortYear": 2000.2,
      "title": "The Camarilla Names the Cathayan Problem",
      "summary": "The Inner Circle studies the NPM as a strategic threat and authorizes containment. A Toreador justicar attempts negotiation, but Sabbat interference collapses the meeting and accelerates west coast destabilization.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Camarilla", "New Promise Mandarinate", "Sabbat"],
      "locations": ["Los Angeles", "San Francisco", "American West"],
      "npcs": ["Sandhurst"],
      "sources": ["shadow-war", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Explains why the Camarilla later returns to LA with policy, not just opportunism."
    },
    {
      "id": "gates-of-hell",
      "era": "demon-reckoning",
      "date": "2002",
      "sortYear": 2002,
      "title": "The Gates of Hell Open Toward Los Angeles",
      "summary": "Escaped Fallen come to Los Angeles seeking the same cultural leverage that drew Lucifer. The city's Infernal Court forms around influence, faith, and the suspicion that the Morningstar is near.",
      "spheres": ["Demon"],
      "factions": ["Fallen", "Infernal Court"],
      "locations": ["Los Angeles", "Hollywood"],
      "npcs": ["Lucifer", "Spentu Mainyu"],
      "sources": ["city-of-angels"],
      "continuity": "published",
      "impact": "Turns LA into a global Fallen pilgrimage site."
    },
    {
      "id": "devils-night",
      "era": "demon-reckoning",
      "date": "2002",
      "sortYear": 2002.5,
      "title": "Devil's Night Breaks the City",
      "summary": "Belial, Enshagkushanna, and Manishtusu's schemes culminate in a catastrophic earthquake and five days of civic collapse. The disaster feeds Earthbound plans until Lucifer's brief revelation interrupts the terror with mass religious awe.",
      "spheres": ["Demon"],
      "factions": ["Earthbound", "Fallen", "Infernal Court"],
      "locations": ["Los Angeles", "City Hall", "Catalina Island"],
      "npcs": ["Belial", "Enshagkushanna", "Manishtusu", "Lucifer"],
      "sources": ["city-of-angels"],
      "continuity": "published",
      "impact": "Creates the major Demon-era rupture that future LA chronicles must account for."
    },
    {
      "id": "infernal-court-politics",
      "era": "demon-reckoning",
      "date": "November-December 2002",
      "sortYear": 2002.9,
      "title": "The Infernal Court Reorders Itself",
      "summary": "Baroness Kishar escapes Hell, Lady Anat arrives, and Spentu Mainyu brokers authority within the Infernal Court and Blood Court. Demon politics become courtly, predatory, and deeply tied to LA influence networks.",
      "spheres": ["Demon"],
      "factions": ["Infernal Court", "Blood Court", "Dragon Ministry"],
      "locations": ["Los Angeles"],
      "npcs": ["Baroness Kishar", "Spentu Mainyu", "Lady Anat"],
      "sources": ["city-of-angels"],
      "continuity": "published",
      "impact": "Provides a standing Demon power structure for crossover citybook chapters."
    },
    {
      "id": "lacrix-prince",
      "era": "bloodlines-npm",
      "date": "2003",
      "sortYear": 2003,
      "title": "The Tower Installs LaCroix",
      "summary": "With the ex-Anarchs broken and the NPM rising, the Camarilla moves into Los Angeles and names Sebastian LaCroix prince. Open war follows among the Tower, Sabbat, neo-Anarchs, and Kuei-jin around territory and the Ankaran Sarcophagus.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Camarilla", "Sabbat", "Neo-Anarchs", "Kuei-jin", "New Promise Mandarinate"],
      "locations": ["Los Angeles"],
      "npcs": ["Sebastian LaCroix"],
      "sources": ["vtmb", "pillars-notes"],
      "continuity": "reconciled",
      "impact": "Bridges Bloodlines-era events into the Pillars city history."
    },
    {
      "id": "lacrix-killed",
      "era": "bloodlines-npm",
      "date": "2005",
      "sortYear": 2005,
      "title": "LaCroix Falls to Treachery",
      "summary": "Kuei-jin agents and Camarilla traitors bring down Prince LaCroix. The conflict narrows into a harder struggle between neo-Anarch remnants and the NPM.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Camarilla", "Kuei-jin", "Neo-Anarchs", "New Promise Mandarinate"],
      "locations": ["Los Angeles"],
      "npcs": ["Sebastian LaCroix"],
      "sources": ["vtmb", "pillars-notes"],
      "continuity": "pillars",
      "impact": "Explains why the Camarilla's first return fails before the Pillars setup."
    },
    {
      "id": "edict-succession",
      "era": "bloodlines-npm",
      "date": "2007",
      "sortYear": 2007,
      "title": "The Edict of Succession",
      "summary": "A treaty framework grants Anarch domains conditional legitimacy so long as they avoid open rebellion. The agreement becomes a tool that later factions can perform, abuse, or hollow out.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Camarilla", "Anarchs", "New Promise Mandarinate"],
      "locations": ["Los Angeles"],
      "npcs": [],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Creates the legal fiction later used to mislead Camarilla observers."
    },
    {
      "id": "npm-wins-free-states",
      "era": "bloodlines-npm",
      "date": "2011",
      "sortYear": 2011,
      "title": "The NPM Wins the Free States War",
      "summary": "The Kuei-jin and their western allies defeat the remaining Free State structure. The NPM uses staged Anarch representatives to keep treaty appearances alive while real resistance withers.",
      "spheres": ["Kuei-jin", "Vampire"],
      "factions": ["New Promise Mandarinate", "Anarchs", "Camarilla"],
      "locations": ["Los Angeles", "American West"],
      "npcs": [],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Turns the Anarch Free State from a state into a memory and a disguise."
    },
    {
      "id": "free-states-fall",
      "era": "bloodlines-npm",
      "date": "2013",
      "sortYear": 2013,
      "title": "The Free States Completely Fall",
      "summary": "By 2013, surviving Anarchs remain in hiding but no longer possess the force to challenge the Mandarinate. The legend lives; the institution does not.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Anarchs", "New Promise Mandarinate"],
      "locations": ["Los Angeles"],
      "npcs": [],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Defines the political vacuum that the Camarilla misreads."
    },
    {
      "id": "false-anarchs-destroyed",
      "era": "bloodlines-npm",
      "date": "2014",
      "sortYear": 2014,
      "title": "The Treaty Masquerade Breaks",
      "summary": "The NPM-aligned actors posing as Anarch treaty partners are destroyed in internal wu conflicts. Their absence alerts the Camarilla that the Edict may no longer be functioning.",
      "spheres": ["Kuei-jin", "Vampire"],
      "factions": ["New Promise Mandarinate", "Camarilla"],
      "locations": ["Los Angeles"],
      "npcs": [],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Triggers the Camarilla's preparation for a direct western intervention."
    },
    {
      "id": "archon-raids",
      "era": "pillars-setup",
      "date": "2015",
      "sortYear": 2015,
      "title": "Archons Break the NPM",
      "summary": "Camarilla Archons under Toreador and Tremere mandates launch lightning raids against the NPM, killing a major portion of its western vampire population. The Tower declares the city safe enough to invite new Kindred in.",
      "spheres": ["Vampire", "Kuei-jin"],
      "factions": ["Camarilla", "Toreador", "Tremere", "New Promise Mandarinate"],
      "locations": ["Los Angeles", "American West"],
      "npcs": [],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Creates the immediate opening for the Pillars of Salt court."
    },
    {
      "id": "perkins-prince",
      "era": "pillars-setup",
      "date": "2015",
      "sortYear": 2015.1,
      "title": "Prince Perkins Takes a Shaky Throne",
      "summary": "Prince Perkins of Clan Ventrue rises as controller of the domain, but his totalitarian instincts outrun his practical grasp on Los Angeles. The new court begins with authority and fragility intertwined.",
      "spheres": ["Vampire"],
      "factions": ["Camarilla", "Ventrue"],
      "locations": ["Los Angeles"],
      "npcs": ["Prince Perkins"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Defines the first Camarilla ruler the chronicle reacts against."
    },
    {
      "id": "giovanni-orange-county",
      "era": "pillars-setup",
      "date": "2015",
      "sortYear": 2015.2,
      "title": "The Giovanni Take Orange County",
      "summary": "Clan Giovanni claims Orange County as a personal domain and names Bruno Giovanni as capo. Necromantic business interests become a formal territorial power beside the Camarilla domain.",
      "spheres": ["Vampire", "Wraith"],
      "factions": ["Giovanni"],
      "locations": ["Orange County"],
      "npcs": ["Bruno Giovanni"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Gives Orange County a distinct necromantic political identity."
    },
    {
      "id": "sabbat-rise-2015",
      "era": "pillars-setup",
      "date": "2015",
      "sortYear": 2015.3,
      "title": "The Sabbat Rise from the Burial Rite",
      "summary": "The hidden Sabbat emerge from Elijah's old ritual as Manishtusu regains strength. Don Dominic De Guzman claims the archdiocese and tries to make Los Angeles worth holding for nomad packs.",
      "spheres": ["Vampire", "Demon"],
      "factions": ["Sabbat", "Earthbound"],
      "locations": ["Los Angeles"],
      "npcs": ["Manishtusu", "Don Dominic De Guzman", "Elijah"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Reintroduces the Sabbat as a living Pillars threat instead of a historical footnote."
    },
    {
      "id": "pictor-blood-hunt",
      "era": "pillars-setup",
      "date": "2015",
      "sortYear": 2015.4,
      "title": "Daphne Pictor Turns the Court",
      "summary": "As confidence in Perkins collapses, he departs for London. Seneschal Daphne Pictor uses the opening to convince the court to name her prince and blood hunt her predecessor.",
      "spheres": ["Vampire"],
      "factions": ["Camarilla", "Tremere", "Ventrue"],
      "locations": ["Los Angeles", "London"],
      "npcs": ["Daphne Pictor", "Prince Perkins"],
      "sources": ["pillars-notes"],
      "continuity": "pillars",
      "impact": "Sets the immediate political frame for the Pillars of Salt chronicle."
    }
  ],
  "factions": [
    {
      "id": "camarilla",
      "name": "Camarilla",
      "sphere": "Vampire",
      "summary": "The Tower treats Los Angeles as a strategic embarrassment, then an opportunity. Its return is built on Archon violence, brittle princes, and claims of order over a city that hates being owned."
    },
    {
      "id": "anarchs",
      "name": "Anarchs",
      "sphere": "Vampire",
      "summary": "The Free State's legacy remains spiritually powerful even after its institutions are broken. Anarch language is used by rebels, collaborators, and NPM puppets alike."
    },
    {
      "id": "sabbat",
      "name": "Sabbat",
      "sphere": "Vampire",
      "summary": "The Sabbat in LA survives through infiltration, burial, prophecy, and opportunistic re-emergence. It is not always visible, but it is rarely absent."
    },
    {
      "id": "npm",
      "name": "New Promise Mandarinate",
      "sphere": "Kuei-jin",
      "summary": "The NPM is born from invasion failure, political adaptation, and divided Anarch leadership. It rules through coalition, pressure, and carefully staged legitimacy."
    },
    {
      "id": "infernal-court",
      "name": "Infernal Court",
      "sphere": "Demon",
      "summary": "The Infernal Court organizes Fallen and Earthbound ambitions around Hollywood, faith, and the aftermath of Devil's Night."
    },
    {
      "id": "giovanni",
      "name": "Giovanni",
      "sphere": "Vampire",
      "summary": "The Giovanni claim Orange County as a family domain, making necromancy, finance, and the dead part of regional politics."
    },
    {
      "id": "pacifica",
      "name": "Kingdom of Pacifica",
      "sphere": "Changeling",
      "summary": "The Changeling court overlays California with its own politics, succession wounds, and glamour debts."
    }
  ],
  "locations": [
    {
      "id": "los-angeles",
      "name": "Los Angeles",
      "summary": "The central domain: a city of film, riots, revolutions, courts, invasions, and competing supernatural myths."
    },
    {
      "id": "hollywood",
      "name": "Hollywood",
      "summary": "The city's dream engine. Vampires, Fallen, Setites, and mortal industries all recognize its power to manufacture desire."
    },
    {
      "id": "catalina",
      "name": "Catalina Island",
      "summary": "A sacred and infernal landmark linked to Enshagkushanna, Tongva mythic history, and Earthbound strategy."
    },
    {
      "id": "orange-county",
      "name": "Orange County",
      "summary": "A separate regional power base that moves from Anarch barony politics toward Giovanni control in Pillars continuity."
    },
    {
      "id": "torrance",
      "name": "Torrance",
      "summary": "A South Bay domain marked by Bishop Mark, Double Helix, and Sabbat Blood Brother experiments."
    },
    {
      "id": "necropolis",
      "name": "Los Angeles Necropolis",
      "summary": "The dead reflection of the city, contested during the Yellow Springs campaign and scarred by the Sixth Great Maelstrom."
    }
  ],
  "hooks": [
    {
      "id": "hollywood-faith-engine",
      "title": "The Hollywood Faith Engine",
      "summary": "Every faction understands Hollywood differently: propaganda machine, feeding ground, infernal temple, glamour furnace, or mortal cover. Whoever controls the story controls more than kine attention."
    },
    {
      "id": "free-state-ghost",
      "title": "The Ghost of the Free State",
      "summary": "The Anarch Free State is gone as a government but alive as an accusation. The city is full of people claiming to restore, avenge, or exploit it."
    },
    {
      "id": "buried-sabbat-debt",
      "title": "The Buried Sabbat Debt",
      "summary": "Elijah's rite saved the Sabbat from destruction but tied them to Manishtusu's hunger. Survivors may not agree on whether they escaped a miracle or a delayed execution."
    },
    {
      "id": "orange-county-dead-ledgers",
      "title": "Orange County's Dead Ledgers",
      "summary": "The Giovanni claim is political, financial, and necromantic. Every real estate transfer may have a ghost attached."
    }
  ],
  "pdfPipeline": {
    "status": "planned",
    "recommendedNextFiles": ["chronicle-print.html", "chronicle-print.css"],
    "bookSections": [
      "Title and legal pages",
      "Table of contents",
      "Timeline chapters by LA history era",
      "Faction dossiers",
      "District and domain guide",
      "NPC appendix",
      "Story hooks and chronicle seeds",
      "Source citations and compliance notes"
    ]
  }
}
;
